# Generated by Django 4.1 on 2022-08-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='super_heroe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.superheroe'),
        ),
    ]
